import test from "node:test";
import assert from "node:assert/strict";
import { AccountCreditClient } from "../lib/billing/account-credits.ts";

const workspaceId="22222222-2222-4222-8222-222222222222";const accountId="11111111-1111-4111-8111-111111111111";const reservationId="33333333-3333-4333-8333-333333333333";
const response={reservationId,workspaceId,runId:"run-1",reservedCredits:200,settledCredits:0,state:"RESERVED",rateCardRevision:3,expiresAt:"2026-07-29T00:00:00.000Z"};
test("platform reserves immutable-rate-card Credits without sending tenant authority in headers",async()=>{let requestBody;const client=new AccountCreditClient({endpoint:"http://account-api:4100",serviceToken:"service-token",allowInsecureLocal:true,fetch:async(_url,init)=>{assert.equal(init.headers.authorization,"Bearer service-token");requestBody=JSON.parse(init.body);return new Response(JSON.stringify({data:response}),{status:200,headers:{"content-type":"application/json"}});}});const value=await client.reserve({workspaceId,accountId,projectId:"project-1",runId:"run-1",amountCredits:200,meter:"MODEL",idempotencyKey:"run-1:model",rateCardRevision:3});assert.equal(value.reservedCredits,200);assert.equal(requestBody.rateCardRevision,3);});
test("platform can idempotently settle or cancel a reservation",async()=>{const paths=[];const client=new AccountCreditClient({endpoint:"http://account-api:4100",serviceToken:"service-token",allowInsecureLocal:true,fetch:async(url)=>{paths.push(new URL(url).pathname);return new Response(JSON.stringify({data:response}),{status:200,headers:{"content-type":"application/json"}});}});await client.settle(workspaceId,reservationId,120);await client.cancel(workspaceId,reservationId);assert.deepEqual(paths,[`/internal/v1/usage/reservations/${reservationId}/settle`,`/internal/v1/usage/reservations/${reservationId}/cancel`]);});
test("insufficient Credit is a stable workflow signal",async()=>{const client=new AccountCreditClient({endpoint:"http://account-api:4100",serviceToken:"service-token",allowInsecureLocal:true,fetch:async()=>new Response("",{status:402})});await assert.rejects(()=>client.reserve({workspaceId,accountId,projectId:"project-1",runId:"run-1",amountCredits:200,meter:"MODEL",idempotencyKey:"run-1:model",rateCardRevision:3}),/INSUFFICIENT_CREDITS/);});
