import test from "node:test";
import assert from "node:assert/strict";
import { AccountPlatformClient, accountSessionToken } from "../lib/auth/account-platform.ts";

const principal={accountId:"11111111-1111-4111-8111-111111111111",email:"player@example.com",displayName:"Player",avatarUrl:null,workspaceId:"22222222-2222-4222-8222-222222222222",workspaceSlug:"player-workspace",workspaceName:"Player workspace",membershipId:"33333333-3333-4333-8333-333333333333",role:"Owner",platformRole:"TenantAdmin",sessionId:"44444444-4444-4444-8444-444444444444"};
test("account platform maps a workspace-scoped assertion without trusting browser tenant fields",async()=>{let called=false;const client=new AccountPlatformClient({endpoint:"http://account-api:4100",serviceToken:"service-token",allowInsecureLocal:true,fetch:async(_url,init)=>{called=true;assert.equal(init.headers.authorization,"Bearer service-token");return new Response(JSON.stringify({data:{principal,githubUserId:12345}}),{status:200,headers:{"content-type":"application/json"}});}});const session=await client.assert("a".repeat(43));assert.equal(called,true);assert.equal(session.tenantId,principal.workspaceId);assert.equal(session.githubUserId,12345);assert.equal(session.githubLinked,true);});
test("email-only sessions receive a stable non-authoritative id and remain marked unlinked",async()=>{const client=new AccountPlatformClient({endpoint:"http://account-api:4100",serviceToken:"service-token",allowInsecureLocal:true,fetch:async()=>new Response(JSON.stringify({data:{principal,githubUserId:null}}),{status:200,headers:{"content-type":"application/json"}})});const session=await client.assert("b".repeat(43));assert.equal(session.githubLinked,false);assert.ok(session.githubUserId>0);});
test("local and secure cookie names are accepted but duplicate cookies are rejected",()=>{assert.equal(accountSessionToken(new Request("http://localhost",{headers:{cookie:`deviludo-session=${"x".repeat(43)}`}})),"x".repeat(43));assert.throws(()=>accountSessionToken(new Request("http://localhost",{headers:{cookie:"deviludo-session=a; deviludo-session=b"}})),/Duplicate/);});

