BEGIN;

-- A workflow iteration owns its output revision even when the generated bytes
-- are identical to an earlier revision. Revision identity remains protected by
-- the primary key and relative-path validation; rejecting a repeated content
-- digest turns an immutable publication into a retry loop after the executor
-- has already saved its completion checkpoint.
ALTER TABLE deviludo.project_source_revisions
  DROP CONSTRAINT IF EXISTS project_source_revisions_workspace_id_project_id_content_di_key;

COMMIT;
