const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
const METERS=new Set(["MODEL","AGENT_MICROVM","E2E_LINUX","E2E_WINDOWS","E2E_MACOS","STORAGE"]);
export type AccountUsageMeter="MODEL"|"AGENT_MICROVM"|"E2E_LINUX"|"E2E_WINDOWS"|"E2E_MACOS"|"STORAGE";
export interface CreditReservation{reservationId:string;workspaceId:string;runId:string;reservedCredits:number;settledCredits:number;state:"RESERVED"|"SETTLED"|"CANCELED";rateCardRevision:number;expiresAt:string}

export class AccountCreditClient{
  readonly #origin:URL;readonly #token:string;readonly #fetch:typeof fetch;
  constructor(options:{endpoint:string;serviceToken:string;allowInsecureLocal?:boolean;fetch?:typeof fetch}){const endpoint=new URL(options.endpoint);const local=options.allowInsecureLocal===true&&endpoint.protocol==="http:"&&!endpoint.username&&!endpoint.password&&!endpoint.search&&!endpoint.hash;if((endpoint.protocol!=="https:"&&!local)||endpoint.pathname!=="/"||!options.serviceToken||options.serviceToken.length>512)throw new Error("Account Credit configuration is invalid");this.#origin=endpoint;this.#token=options.serviceToken;this.#fetch=options.fetch??fetch;}
  async reserve(input:{workspaceId:string;accountId:string;projectId:string;runId:string;amountCredits:number;meter:AccountUsageMeter;idempotencyKey:string;rateCardRevision:number}):Promise<CreditReservation>{if(!UUID.test(input.workspaceId)||!UUID.test(input.accountId)||!input.projectId||!input.runId||!Number.isSafeInteger(input.amountCredits)||input.amountCredits<1||!METERS.has(input.meter)||!input.idempotencyKey||!Number.isSafeInteger(input.rateCardRevision)||input.rateCardRevision<1)throw new Error("Credit reservation is invalid");return this.#request("/internal/v1/usage/reservations",input);}
  async settle(workspaceId:string,reservationId:string,actualCredits:number):Promise<CreditReservation>{if(!UUID.test(workspaceId)||!UUID.test(reservationId)||!Number.isSafeInteger(actualCredits)||actualCredits<0)throw new Error("Credit settlement is invalid");return this.#request(`/internal/v1/usage/reservations/${reservationId}/settle`,{workspaceId,actualCredits});}
  async cancel(workspaceId:string,reservationId:string):Promise<CreditReservation>{if(!UUID.test(workspaceId)||!UUID.test(reservationId))throw new Error("Credit cancellation is invalid");return this.#request(`/internal/v1/usage/reservations/${reservationId}/cancel`,{workspaceId});}
  async #request(path:string,body:Record<string,unknown>):Promise<CreditReservation>{let response:Response;try{response=await this.#fetch(new URL(path,this.#origin),{method:"POST",redirect:"error",headers:{accept:"application/json","content-type":"application/json",authorization:`Bearer ${this.#token}`},body:JSON.stringify(body),signal:AbortSignal.timeout(15_000)});}catch{throw new Error("Account Credit service is unavailable");}if(response.status===402)throw new Error("INSUFFICIENT_CREDITS");if(!response.ok)throw new Error("Account Credit service rejected the operation");const value=await response.json() as {data?:Record<string,unknown>};return reservation(value.data);}
}

export function accountCreditClientFromEnvironment(env:Readonly<Record<string,string|undefined>>=process.env):AccountCreditClient|null{const endpoint=env.DEVILUDO_ACCOUNT_API_URL?.trim();if(!endpoint)return null;const serviceToken=env.DEVILUDO_INTERNAL_SERVICE_TOKEN?.trim();if(!serviceToken)throw new Error("DEVILUDO_INTERNAL_SERVICE_TOKEN is required");return new AccountCreditClient({endpoint,serviceToken,allowInsecureLocal:env.DEVILUDO_ACCOUNT_ALLOW_INSECURE_LOCAL==="1"});}
function reservation(value:Record<string,unknown>|undefined):CreditReservation{if(!value||!UUID.test(String(value.reservationId))||!UUID.test(String(value.workspaceId))||typeof value.runId!=="string"||!value.runId||typeof value.reservedCredits!=="number"||!Number.isSafeInteger(value.reservedCredits)||typeof value.settledCredits!=="number"||!Number.isSafeInteger(value.settledCredits)||!(["RESERVED","SETTLED","CANCELED"] as unknown[]).includes(value.state)||typeof value.rateCardRevision!=="number"||!Number.isSafeInteger(value.rateCardRevision)||typeof value.expiresAt!=="string"||!Number.isFinite(Date.parse(value.expiresAt)))throw new Error("Account Credit response is invalid");return Object.freeze(value) as unknown as CreditReservation;}
