export const E2E_EVIDENCE_SCHEMA: "deviludo.e2e-evidence";
export const GUEST_REPORT_SCHEMA: "deviludo.godot-guest-report";
export const E2E_EVIDENCE_MANIFEST_SCHEMA: "deviludo.e2e-evidence-manifest";
export const E2E_CLIENT_WIDTH: number;
export const E2E_CLIENT_HEIGHT: number;
export const DEFAULT_VISUAL_THRESHOLD: number;
export const MAX_SOLID_PIXEL_RATIO: number;
export const MIN_OPAQUE_PIXEL_RATIO: number;
export const MAX_E2E_EVIDENCE_BYTES: number;
export const MAX_E2E_VIDEO_BYTES: number;
export function godotErrorLines(...logs: unknown[]): string[];
export function inspectScreenshot(path: string, expectedWidth?: number, expectedHeight?: number): Promise<Readonly<Record<string, unknown>>>;
export function captureAndInspectScreenshot(path: string, capture: (path: string) => Promise<unknown>, options?: Readonly<{ attempts?: number; delayMs?: number }>): Promise<Readonly<Record<string, unknown>>>;
export function compareScreenshots(actualPath: string, referencePath: string, diffPath?: string, threshold?: number): Promise<Readonly<{ passed: boolean; differentPixels: number; totalPixels: number; differenceRatio: number; threshold: number }>>;
export function compareScreenshotRegion(actualPath: string, referencePath: string, rect: Readonly<{ x: number; y: number; width: number; height: number }>, diffPath?: string | null): Promise<Readonly<{ differentPixels: number; totalPixels: number; differenceRatio: number; region: Readonly<{ x: number; y: number; width: number; height: number }> }>>;
export function encodeRgbaPng(width: number, height: number, rgba: Buffer): Buffer;
export function createEvidenceBundle(input: Readonly<Record<string, unknown>>): Promise<Readonly<{ outputPath: string; outputSha256: string; outputSizeBytes: number; manifest: Readonly<Record<string, unknown>> }>>;
export function extractAndValidateEvidenceBundle(zipPath: string, destination: string, maximumBytes?: number): Promise<Readonly<{ manifest: Readonly<Record<string, unknown>>; report: Readonly<Record<string, unknown>>; indexPath: string }>>;
export function readEvidenceRepairContext(zipPath: string, maximumBytes?: number): Promise<Readonly<{ report: Readonly<Record<string, unknown>>; screenshots: readonly Readonly<Record<string, unknown>>[] }>>;
