import { spawn, type ChildProcess } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { isAbsolute, join, resolve, sep } from "node:path";
import { CODEX_ACCOUNT_DEFAULT_MODEL } from "@/lib/product/contracts";
import { usesCodexOfficialLogin } from "./agent-settings";

export type CodexPromptInput = Readonly<{
  baseUrl: string;
  credential: string;
  model: string;
  prompt: string;
  imageBase64?: string;
  outputSchema?: Readonly<Record<string, unknown>>;
  reasoningEffort?: "low" | "medium" | "high" | "xhigh";
  timeoutMs?: number;
}>;

export type CodexPromptRunner = (input: CodexPromptInput) => Promise<string>;

export type CodexImageInput = Readonly<{
  baseUrl: string;
  credential: string;
  model: string;
  prompt: string;
  timeoutMs?: number;
}>;

export type CodexImageRunner = (input: CodexImageInput) => Promise<Buffer>;

const MAX_CODEX_IMAGE_BYTES = 8 * 1024 * 1024;
const MAX_CODEX_OUTPUT_BYTES = 8 * 1024 * 1024;
const MAX_CODEX_DIAGNOSTIC_BYTES = 64 * 1024;
const MAX_CODEX_MODELS_CACHE_BYTES = 8 * 1024 * 1024;
const CODEX_TERMINATION_GRACE_MS = 2_000;
const CODEX_CLIENT_VERSION = /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;

export function resolveCodexExecutionModel(
  requestedModel: string,
  accountDefaultModel = process.env.DEVILUDO_CODEX_ACCOUNT_DEFAULT_MODEL?.trim() ?? "",
): string {
  if (requestedModel !== CODEX_ACCOUNT_DEFAULT_MODEL || !accountDefaultModel) return requestedModel;
  if (accountDefaultModel === CODEX_ACCOUNT_DEFAULT_MODEL
    || !/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$/.test(accountDefaultModel)) {
    throw new Error("Codex account default model metadata is invalid");
  }
  return accountDefaultModel;
}

export function resolveCodexRunRoot(
  configuredRoot = process.env.DEVILUDO_CODEX_RUN_ROOT?.trim() || join(homedir(), ".deviludo", "codex-runs"),
  temporaryRoot = tmpdir(),
): string {
  if (!isAbsolute(configuredRoot)) throw new Error("Codex run root must be absolute");
  const root = resolve(configuredRoot);
  const temporary = resolve(temporaryRoot);
  if (root === temporary || root.startsWith(`${temporary}${sep}`)) {
    throw new Error("Codex run root cannot be inside the system temporary directory");
  }
  return root;
}

export async function runCodexPrompt(input: CodexPromptInput): Promise<string> {
  const official = usesCodexOfficialLogin(input.baseUrl);
  validateCodexCredential(input.credential, official);
  const root = await createCodexRun("prompt");
  try {
    const hasStaticCatalog = await prepareCodexHome(root, input.credential, official);
    const args = codexExecutionArgs(input.baseUrl, hasStaticCatalog ? join(root, "model-catalog.json") : null);
    const executionModel = resolveCodexExecutionModel(input.model);
    if (executionModel !== CODEX_ACCOUNT_DEFAULT_MODEL) args.push("-m", executionModel);
    if (input.reasoningEffort) {
      args.push("--config", `model_reasoning_effort=${input.reasoningEffort}`);
    }
    args.push("-C", root);
    if (input.imageBase64) {
      const image = join(root, "frame.png");
      await writeFile(image, Buffer.from(input.imageBase64, "base64"), { mode: 0o600 });
      args.push("--image", image);
    }
    if (input.outputSchema) {
      const schema = join(root, "output-schema.json");
      const serialized = JSON.stringify(input.outputSchema);
      if (serialized.length > 256 * 1024) throw new Error("Codex output schema exceeds the size limit");
      await writeFile(schema, serialized, { mode: 0o600 });
      args.push("--output-schema", schema);
    }
    args.push("-");
    return await executeCodex(args, input.prompt, root, input.timeoutMs ?? 180_000, true,
      official ? {} : { DEVILUDO_CODEX_PROVIDER_API_KEY: input.credential });
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

/**
 * Generate one image through Codex's built-in ImageGen tool.
 *
 * The selected Codex text model orchestrates the tool call; the image model is
 * the runtime-owned gpt-image-2 and is intentionally not configurable here. The
 * generated bytes are discovered under the isolated CODEX_HOME instead of being
 * accepted from the Agent's final prose, so a claimed success without an actual
 * image cannot advance the asset gate.
 */
export async function runCodexImage(input: CodexImageInput): Promise<Buffer> {
  const official = usesCodexOfficialLogin(input.baseUrl);
  validateCodexCredential(input.credential, official);
  const root = await createCodexRun("image");
  try {
    const hasStaticCatalog = await prepareCodexHome(root, input.credential, official);
    const args = codexExecutionArgs(input.baseUrl, hasStaticCatalog ? join(root, "model-catalog.json") : null);
    args.push("--enable", "image_generation", "--sandbox", "read-only");
    const executionModel = resolveCodexExecutionModel(input.model);
    if (executionModel !== CODEX_ACCOUNT_DEFAULT_MODEL) args.push("-m", executionModel);
    args.push("-C", root, "-");
    await executeCodex(args, codexImageInstruction(input.prompt), root, input.timeoutMs ?? 300_000, false,
      official ? {} : { DEVILUDO_CODEX_PROVIDER_API_KEY: input.credential });
    const candidates = await generatedImages(join(root, "generated_images"));
    if (candidates.length !== 1) {
      throw new Error(candidates.length === 0
        ? "Codex ImageGen did not produce an image"
        : "Codex ImageGen produced more than one image");
    }
    const metadata = await stat(candidates[0]);
    if (!metadata.isFile() || metadata.size < 1) throw new Error("Codex ImageGen returned an empty image");
    if (metadata.size > MAX_CODEX_IMAGE_BYTES) throw new Error("Codex ImageGen image exceeds the size limit");
    return await readFile(candidates[0]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

async function createCodexRun(prefix: "prompt" | "image"): Promise<string> {
  const parent = resolveCodexRunRoot();
  await mkdir(parent, { recursive: true, mode: 0o700 });
  return mkdtemp(join(parent, `${prefix}-`));
}

async function prepareCodexHome(root: string, credential: string, official: boolean): Promise<boolean> {
  if (!official) return false;
  await writeFile(join(root, "auth.json"), credential, { mode: 0o600 });
  return installCodexModelsCache(root);
}

/**
 * Seed each isolated CODEX_HOME with the host CLI's non-secret model catalogue.
 * `model_catalog_json` selects Codex's static model manager; a cache alone still
 * starts an asynchronous provider refresh even when `-m` is explicit. The API
 * cache omits one protocol field, so default it conservatively when producing
 * the static startup catalogue.
 */
export async function installCodexModelsCache(
  codexHome: string,
  source = process.env.DEVILUDO_CODEX_MODELS_CACHE_FILE?.trim() ?? "",
  bundledCliVersion = process.env.DEVILUDO_BUNDLED_CODEX_CLI_VERSION?.trim() ?? "",
): Promise<boolean> {
  if (!source) return false;
  if (!isAbsolute(source)) throw new Error("Codex models cache path must be absolute");
  if (bundledCliVersion && !CODEX_CLIENT_VERSION.test(bundledCliVersion)) {
    throw new Error("Bundled Codex CLI version metadata is invalid");
  }
  const metadata = await stat(source);
  if (!metadata.isFile() || metadata.size < 2 || metadata.size > MAX_CODEX_MODELS_CACHE_BYTES) {
    throw new Error("Codex models cache file is invalid");
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(await readFile(source, "utf8"));
  } catch {
    throw new Error("Codex models cache file is invalid");
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)
    || !Array.isArray((parsed as { models?: unknown }).models)
    || typeof (parsed as { client_version?: unknown }).client_version !== "string"
    || !CODEX_CLIENT_VERSION.test((parsed as { client_version: string }).client_version)) {
    throw new Error("Codex models cache file is invalid");
  }
  if (bundledCliVersion
    && (parsed as { client_version: string }).client_version !== bundledCliVersion) {
    throw new Error("Codex models cache does not match the bundled CLI version");
  }
  const models = (parsed as { models: unknown[] }).models.map(model => {
    if (!model || typeof model !== "object" || Array.isArray(model)) {
      throw new Error("Codex models cache file is invalid");
    }
    const supportsParallelToolCalls = (model as { supports_parallel_tool_calls?: unknown }).supports_parallel_tool_calls;
    if (supportsParallelToolCalls !== undefined && typeof supportsParallelToolCalls !== "boolean") {
      throw new Error("Codex models cache file is invalid");
    }
    return {
      ...model as Record<string, unknown>,
      supports_parallel_tool_calls: supportsParallelToolCalls ?? false,
    };
  });
  await writeFile(join(codexHome, "models_cache.json"), JSON.stringify(parsed), { mode: 0o600 });
  await writeFile(join(codexHome, "model-catalog.json"), JSON.stringify({ models }), { mode: 0o600 });
  return true;
}

function codexExecutionArgs(baseUrl: string, modelCatalog: string | null): string[] {
  const official = usesCodexOfficialLogin(baseUrl);
  const provider = official ? "deviludo_chatgpt" : "deviludo_custom";
  const args = [
    "exec",
    "--ephemeral",
    "--json",
    "--ignore-user-config",
    "--config", `model_provider=${provider}`,
    "--config", `model_providers.${provider}.name=${official ? "OpenAI" : "DeviLudo custom Provider"}`,
    "--config", `model_providers.${provider}.base_url=${official ? "https://chatgpt.com/backend-api/codex" : baseUrl}`,
    "--config", `model_providers.${provider}.wire_api=responses`,
    "--config", `model_providers.${provider}.requires_openai_auth=${official}`,
    "--config", `model_providers.${provider}.supports_websockets=false`,
    "--skip-git-repo-check",
  ];
  if (!official) args.push("--config", `model_providers.${provider}.env_key=DEVILUDO_CODEX_PROVIDER_API_KEY`);
  if (modelCatalog) args.push("--config", `model_catalog_json=${modelCatalog}`);
  return args;
}

function codexImageInstruction(prompt: string): string {
  return [
    "Call the built-in image generation tool exactly once for the prompt below.",
    "Do not use shell commands, code, SVG, HTML, or placeholder files to create the image.",
    "Do not inspect the filesystem or authentication files. Finish only after the built-in tool has produced one image.",
    "IMAGE PROMPT:",
    prompt,
  ].join("\n");
}

async function generatedImages(root: string): Promise<readonly string[]> {
  const found: string[] = [];
  async function visit(directory: string): Promise<void> {
    let entries;
    try {
      entries = await readdir(directory, { withFileTypes: true });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
    for (const entry of entries) {
      if (found.length > 4) return;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await visit(path);
      else if (entry.isFile() && /\.(?:png|jpe?g|webp)$/i.test(entry.name)) found.push(path);
    }
  }
  await visit(root);
  return Object.freeze(found);
}

function validateCodexCredential(value: string, official: boolean): void {
  if (!official) {
    if (value.length < 8 || value.length > 4096 || /[\u0000-\u001f\u007f]/.test(value)) {
      throw new Error("Codex Provider API Key is invalid");
    }
    return;
  }
  let parsed: unknown;
  try { parsed = JSON.parse(value); } catch { throw new Error("Codex official login data is invalid"); }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("Codex official login data is invalid");
  }
}

function executeCodex(
  args: readonly string[],
  prompt: string,
  codexHome: string,
  timeoutMs: number,
  requireAgentMessage = true,
  providerEnvironment: Readonly<Record<string, string>> = {},
): Promise<string> {
  return new Promise((resolve, reject) => {
    const proxy = process.env.DEVILUDO_CODEX_PROXY_URL?.trim();
    if (proxy && !/^http:\/\/[a-z0-9.-]+:\d+$/i.test(proxy)) {
      return reject(new Error("Codex CLI proxy configuration is invalid"));
    }
    const killProcessGroup = process.platform !== "win32";
    const child = spawn("codex", args, {
      shell: false,
      stdio: ["pipe", "pipe", "pipe"],
      // The npm entrypoint starts the native Codex binary as a child process.
      // Give the invocation its own process group so a deadline terminates both
      // processes instead of leaving the native binary running in Core.
      detached: killProcessGroup,
      env: {
        ...process.env,
        CODEX_HOME: codexHome,
        ...providerEnvironment,
        ...(proxy ? { HTTP_PROXY: proxy, HTTPS_PROXY: proxy, ALL_PROXY: proxy } : {}),
      },
    });
    const stdout: Buffer[] = [];
    const stderr: Buffer[] = [];
    let stdoutBytes = 0;
    let stderrBytes = 0;
    let termination: "timeout" | "output-limit" | null = null;
    let forceTimer: NodeJS.Timeout | null = null;
    let settled = false;
    const terminate = (reason: "timeout" | "output-limit") => {
      if (termination) return;
      termination = reason;
      signalCodexProcessTree(child, "SIGTERM", killProcessGroup);
      forceTimer = setTimeout(
        () => signalCodexProcessTree(child, "SIGKILL", killProcessGroup),
        CODEX_TERMINATION_GRACE_MS,
      );
      forceTimer.unref?.();
    };
    const timer = setTimeout(() => terminate("timeout"), timeoutMs);
    timer.unref?.();
    const cleanup = () => {
      clearTimeout(timer);
      if (forceTimer) clearTimeout(forceTimer);
    };
    child.stdout.on("data", chunk => {
      stdoutBytes += chunk.length;
      if (stdoutBytes <= MAX_CODEX_OUTPUT_BYTES) stdout.push(Buffer.from(chunk));
      else terminate("output-limit");
    });
    child.stderr.on("data", chunk => {
      if (stderrBytes >= MAX_CODEX_DIAGNOSTIC_BYTES) return;
      const buffered = Buffer.from(chunk).subarray(0, MAX_CODEX_DIAGNOSTIC_BYTES - stderrBytes);
      stderrBytes += buffered.length;
      stderr.push(buffered);
    });
    child.once("error", error => {
      if (settled) return;
      settled = true;
      cleanup();
      reject(error);
    });
    child.once("close", (code, signal) => {
      if (settled) return;
      settled = true;
      // Also signal the group after the npm entrypoint exits: a descendant may
      // have closed its inherited pipes but still be alive in the same group.
      if (termination) signalCodexProcessTree(child, "SIGKILL", killProcessGroup);
      cleanup();
      const stdoutText = Buffer.concat(stdout).toString("utf8");
      const diagnostic = (
        Buffer.concat(stderr).toString("utf8").trim()
        || extractCodexFailure(stdoutText)
      ).slice(0, 500);
      if (termination === "timeout") {
        return reject(new Error(`Codex CLI timed out after ${timeoutMs} ms${diagnostic ? `: ${diagnostic}` : ""}`));
      }
      if (termination === "output-limit") return reject(new Error("Codex CLI output exceeded the size limit"));
      if (code !== 0) return reject(new Error(`Codex CLI failed (${code ?? signal ?? "signal"}): ${diagnostic}`));
      const text = extractAgentMessage(stdoutText);
      if (!text && requireAgentMessage) return reject(new Error("Codex CLI did not return an Agent message"));
      resolve(text ?? "");
    });
    child.stdin.end(prompt);
  });
}

function signalCodexProcessTree(child: ChildProcess, signal: NodeJS.Signals, killProcessGroup: boolean): void {
  if (killProcessGroup && Number.isSafeInteger(child.pid)) {
    try {
      process.kill(-Number(child.pid), signal);
      return;
    } catch { /* The group may already have exited; fall back to the entrypoint. */ }
  }
  try {
    if (child.exitCode === null && child.signalCode === null) child.kill(signal);
  } catch { /* Process termination is best effort and close/error settles the call. */ }
}

function extractCodexFailure(output: string): string {
  for (const line of output.split(/\r?\n/).reverse()) {
    if (!line.trim()) continue;
    try {
      const event = JSON.parse(line) as Record<string, unknown>;
      if (typeof event.message === "string" && /error|fail/i.test(String(event.type ?? ""))) {
        return event.message;
      }
      const error = event.error && typeof event.error === "object" && !Array.isArray(event.error)
        ? event.error as Record<string, unknown>
        : null;
      if (typeof error?.message === "string") return error.message;
    } catch { /* Ignore non-JSON transport diagnostics. */ }
  }
  return "Codex exited without an error diagnostic";
}

export function extractAgentMessage(output: string): string | null {
  let latest: string | null = null;
  for (const line of output.split(/\r?\n/)) {
    if (!line.trim()) continue;
    try {
      const event = JSON.parse(line) as Record<string, unknown>;
      const item = event.item && typeof event.item === "object" && !Array.isArray(event.item)
        ? event.item as Record<string, unknown>
        : null;
      if (item?.type === "agent_message" && typeof item.text === "string") latest = item.text;
      else if (event.type === "agent_message" && typeof event.message === "string") latest = event.message;
      else if (typeof event.output_text === "string") latest = event.output_text;
    } catch { /* Codex may emit a bounded non-JSON diagnostic line. */ }
  }
  return latest?.trim() || null;
}
