import { spawn } from "node:child_process";
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CODEX_ACCOUNT_DEFAULT_MODEL } from "@/lib/product/contracts";

export type CodexPromptInput = Readonly<{
  authJson: string;
  model: string;
  prompt: string;
  imageBase64?: string;
  reasoningEffort?: "low" | "medium" | "high" | "xhigh";
  timeoutMs?: number;
}>;

export type CodexPromptRunner = (input: CodexPromptInput) => Promise<string>;

export type CodexImageInput = Readonly<{
  authJson: string;
  model: string;
  prompt: string;
  timeoutMs?: number;
}>;

export type CodexImageRunner = (input: CodexImageInput) => Promise<Buffer>;

const MAX_CODEX_IMAGE_BYTES = 8 * 1024 * 1024;

export function resolveCodexExecutionModel(
  requestedModel: string,
  accountDefaultModel = process.env.DEVILUDO_CODEX_ACCOUNT_DEFAULT_MODEL?.trim() ?? "",
): string {
  if (requestedModel !== CODEX_ACCOUNT_DEFAULT_MODEL || !accountDefaultModel) return requestedModel;
  if (accountDefaultModel === CODEX_ACCOUNT_DEFAULT_MODEL
    || !/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}$/.test(accountDefaultModel)) {
    throw new Error("Codex account default model metadata is invalid");
  }
  return accountDefaultModel;
}

export async function runCodexPrompt(input: CodexPromptInput): Promise<string> {
  validateAuth(input.authJson);
  const root = await mkdtemp(join(tmpdir(), "deviludo-codex-"));
  try {
    await writeFile(join(root, "auth.json"), input.authJson, { mode: 0o600 });
    const args = codexExecutionArgs();
    const executionModel = resolveCodexExecutionModel(input.model);
    if (executionModel !== CODEX_ACCOUNT_DEFAULT_MODEL) args.push("-m", executionModel);
    if (input.reasoningEffort) {
      args.push("--config", `model_reasoning_effort=${input.reasoningEffort}`);
    }
    args.push("-C", root);
    if (input.imageBase64) {
      const image = join(root, "frame.png");
      await writeFile(image, Buffer.from(input.imageBase64, "base64"), { mode: 0o600 });
      args.push("--image", image);
    }
    args.push("-");
    return await executeCodex(args, input.prompt, root, input.timeoutMs ?? 180_000);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

/**
 * Generate one image through Codex's built-in ImageGen tool.
 *
 * The selected Codex text model orchestrates the tool call; the image model is
 * the runtime-owned gpt-image-2 and is intentionally not configurable here. The
 * generated bytes are discovered under the isolated CODEX_HOME instead of being
 * accepted from the Agent's final prose, so a claimed success without an actual
 * image cannot advance the asset gate.
 */
export async function runCodexImage(input: CodexImageInput): Promise<Buffer> {
  validateAuth(input.authJson);
  const root = await mkdtemp(join(tmpdir(), "deviludo-codex-image-"));
  try {
    await writeFile(join(root, "auth.json"), input.authJson, { mode: 0o600 });
    const args = codexExecutionArgs();
    args.push("--enable", "image_generation", "--sandbox", "read-only");
    const executionModel = resolveCodexExecutionModel(input.model);
    if (executionModel !== CODEX_ACCOUNT_DEFAULT_MODEL) args.push("-m", executionModel);
    args.push("-C", root, "-");
    await executeCodex(args, codexImageInstruction(input.prompt), root, input.timeoutMs ?? 300_000, false);
    const candidates = await generatedImages(join(root, "generated_images"));
    if (candidates.length !== 1) {
      throw new Error(candidates.length === 0
        ? "Codex ImageGen did not produce an image"
        : "Codex ImageGen produced more than one image");
    }
    const metadata = await stat(candidates[0]);
    if (!metadata.isFile() || metadata.size < 1) throw new Error("Codex ImageGen returned an empty image");
    if (metadata.size > MAX_CODEX_IMAGE_BYTES) throw new Error("Codex ImageGen image exceeds the size limit");
    return await readFile(candidates[0]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function codexExecutionArgs(): string[] {
  return [
    "exec",
    "--ephemeral",
    "--json",
    "--ignore-user-config",
    "--config", "model_provider=deviludo_chatgpt",
    "--config", "model_providers.deviludo_chatgpt.name=OpenAI",
    "--config", "model_providers.deviludo_chatgpt.base_url=https://chatgpt.com/backend-api/codex",
    "--config", "model_providers.deviludo_chatgpt.wire_api=responses",
    "--config", "model_providers.deviludo_chatgpt.requires_openai_auth=true",
    "--config", "model_providers.deviludo_chatgpt.supports_websockets=false",
    "--skip-git-repo-check",
  ];
}

function codexImageInstruction(prompt: string): string {
  return [
    "Call the built-in image generation tool exactly once for the prompt below.",
    "Do not use shell commands, code, SVG, HTML, or placeholder files to create the image.",
    "Do not inspect the filesystem or authentication files. Finish only after the built-in tool has produced one image.",
    "IMAGE PROMPT:",
    prompt,
  ].join("\n");
}

async function generatedImages(root: string): Promise<readonly string[]> {
  const found: string[] = [];
  async function visit(directory: string): Promise<void> {
    let entries;
    try {
      entries = await readdir(directory, { withFileTypes: true });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
    for (const entry of entries) {
      if (found.length > 4) return;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await visit(path);
      else if (entry.isFile() && /\.(?:png|jpe?g|webp)$/i.test(entry.name)) found.push(path);
    }
  }
  await visit(root);
  return Object.freeze(found);
}

function validateAuth(value: string): void {
  let parsed: unknown;
  try { parsed = JSON.parse(value); } catch { throw new Error("Codex official login data is invalid"); }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("Codex official login data is invalid");
  }
}

function executeCodex(
  args: readonly string[],
  prompt: string,
  codexHome: string,
  timeoutMs: number,
  requireAgentMessage = true,
): Promise<string> {
  return new Promise((resolve, reject) => {
    const proxy = process.env.DEVILUDO_CODEX_PROXY_URL?.trim();
    if (proxy && !/^http:\/\/[a-z0-9.-]+:\d+$/i.test(proxy)) {
      return reject(new Error("Codex CLI proxy configuration is invalid"));
    }
    const child = spawn("codex", args, {
      shell: false,
      stdio: ["pipe", "pipe", "pipe"],
      env: {
        ...process.env,
        CODEX_HOME: codexHome,
        ...(proxy ? { HTTP_PROXY: proxy, HTTPS_PROXY: proxy, ALL_PROXY: proxy } : {}),
      },
    });
    const stdout: Buffer[] = [];
    const stderr: Buffer[] = [];
    let bytes = 0;
    const timer = setTimeout(() => child.kill("SIGKILL"), timeoutMs);
    child.stdout.on("data", chunk => {
      bytes += chunk.length;
      if (bytes <= 8 * 1024 * 1024) stdout.push(Buffer.from(chunk));
      else child.kill("SIGKILL");
    });
    child.stderr.on("data", chunk => {
      if (Buffer.concat(stderr).length < 64 * 1024) stderr.push(Buffer.from(chunk));
    });
    child.once("error", error => { clearTimeout(timer); reject(error); });
    child.once("close", code => {
      clearTimeout(timer);
      if (code !== 0) return reject(new Error(`Codex CLI failed (${code ?? "signal"}): ${Buffer.concat(stderr).toString("utf8").slice(0, 500)}`));
      const text = extractAgentMessage(Buffer.concat(stdout).toString("utf8"));
      if (!text && requireAgentMessage) return reject(new Error("Codex CLI did not return an Agent message"));
      resolve(text ?? "");
    });
    child.stdin.end(prompt);
  });
}

export function extractAgentMessage(output: string): string | null {
  let latest: string | null = null;
  for (const line of output.split(/\r?\n/)) {
    if (!line.trim()) continue;
    try {
      const event = JSON.parse(line) as Record<string, unknown>;
      const item = event.item && typeof event.item === "object" && !Array.isArray(event.item)
        ? event.item as Record<string, unknown>
        : null;
      if (item?.type === "agent_message" && typeof item.text === "string") latest = item.text;
      else if (event.type === "agent_message" && typeof event.message === "string") latest = event.message;
      else if (typeof event.output_text === "string") latest = event.output_text;
    } catch { /* Codex may emit a bounded non-JSON diagnostic line. */ }
  }
  return latest?.trim() || null;
}
